using Newtonsoft.Json;

namespace Opaalib.OAuth
{
    public class AccessTokenResponse
    {
        /// <summary>
        /// The unique access token generated by the server.
        /// </summary>
        [JsonProperty(PropertyName = "access_token", Required = Required.Always)]
        public string AccessToken { get; set; }

        /// <summary>
        /// The only supported type is ‘bearer’. 
        /// </summary>
        [JsonProperty(PropertyName = "token_type", Required = Required.Always)]
        public string TokenType { get; set; }

        /// <summary>
        /// The expiration period for tokens. The access token expires in 600 sec.
        /// </summary>
        [JsonProperty(PropertyName = "expires_in", Required = Required.Always)]
        public int ExpiresIn { get; set; }
    }
}